/* soapServiceSoapBindingService.h
   Generated by gSOAP 2.8.12 from service.1cws?wsdl.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapServiceSoapBindingService_H
#define soapServiceSoapBindingService_H
#include "soapH.h"
class SOAP_CMAC ServiceSoapBindingService : public soap
{ public:
	/// Constructor
	ServiceSoapBindingService();
	/// Construct from another engine state
	ServiceSoapBindingService(const struct soap&);
	/// Constructor with engine input+output mode control
	ServiceSoapBindingService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	ServiceSoapBindingService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~ServiceSoapBindingService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void ServiceSoapBindingService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	ServiceSoapBindingService *copy() SOAP_PURE_VIRTUAL;
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'getName' (returns error code or SOAP_OK)
	virtual	int getName(_ns1__getName *ns1__getName, _ns1__getNameResponse *ns1__getNameResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'runCode' (returns error code or SOAP_OK)
	virtual	int runCode(_ns1__runCode *ns1__runCode, _ns1__runCodeResponse *ns1__runCodeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Start' (returns error code or SOAP_OK)
	virtual	int Start(_ns1__Start *ns1__Start, _ns1__StartResponse *ns1__StartResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Status' (returns error code or SOAP_OK)
	virtual	int Status(_ns1__Status *ns1__Status, _ns1__StatusResponse *ns1__StatusResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Stop' (returns error code or SOAP_OK)
	virtual	int Stop(_ns1__Stop *ns1__Stop, _ns1__StopResponse *ns1__StopResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'getName' (returns error code or SOAP_OK)
	virtual	int getName_(_ns1__getName *ns1__getName, _ns1__getNameResponse *ns1__getNameResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'runCode' (returns error code or SOAP_OK)
	virtual	int runCode_(_ns1__runCode *ns1__runCode, _ns1__runCodeResponse *ns1__runCodeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Start' (returns error code or SOAP_OK)
	virtual	int Start_(_ns1__Start *ns1__Start, _ns1__StartResponse *ns1__StartResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Status' (returns error code or SOAP_OK)
	virtual	int Status_(_ns1__Status *ns1__Status, _ns1__StatusResponse *ns1__StatusResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Stop' (returns error code or SOAP_OK)
	virtual	int Stop_(_ns1__Stop *ns1__Stop, _ns1__StopResponse *ns1__StopResponse) SOAP_PURE_VIRTUAL;
};
#endif
