/* soapServiceSoapBindingProxy.cpp
   Generated by gSOAP 2.8.12 from service.1cws?wsdl.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapServiceSoapBindingProxy.h"

ServiceSoapBindingProxy::ServiceSoapBindingProxy()
{	ServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

ServiceSoapBindingProxy::ServiceSoapBindingProxy(const struct soap &_soap) : soap(_soap)
{ }

ServiceSoapBindingProxy::ServiceSoapBindingProxy(const char *url)
{	ServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

ServiceSoapBindingProxy::ServiceSoapBindingProxy(soap_mode iomode)
{	ServiceSoapBindingProxy_init(iomode, iomode);
}

ServiceSoapBindingProxy::ServiceSoapBindingProxy(const char *url, soap_mode iomode)
{	ServiceSoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

ServiceSoapBindingProxy::ServiceSoapBindingProxy(soap_mode imode, soap_mode omode)
{	ServiceSoapBindingProxy_init(imode, omode);
}

ServiceSoapBindingProxy::~ServiceSoapBindingProxy()
{ }

void ServiceSoapBindingProxy::ServiceSoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://localhost/service", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void ServiceSoapBindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void ServiceSoapBindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_init(this);
	ServiceSoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void ServiceSoapBindingProxy::soap_noheader()
{	this->header = NULL;
}

const SOAP_ENV__Header *ServiceSoapBindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *ServiceSoapBindingProxy::soap_fault()
{	return this->fault;
}

const char *ServiceSoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *ServiceSoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int ServiceSoapBindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int ServiceSoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void ServiceSoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void ServiceSoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *ServiceSoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int ServiceSoapBindingProxy::getName(const char *endpoint, const char *soap_action, _ns1__getName *ns1__getName, _ns1__getNameResponse *ns1__getNameResponse)
{	struct soap *soap = this;
	struct __ns1__getName soap_tmp___ns1__getName;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:getName";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getName.ns1__getName = ns1__getName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getName(soap, &soap_tmp___ns1__getName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getName(soap, &soap_tmp___ns1__getName, "-ns1:getName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getName(soap, &soap_tmp___ns1__getName, "-ns1:getName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getNameResponse)
		return soap_closesock(soap);
	ns1__getNameResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getNameResponse->soap_get(soap, "ns1:getNameResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::runCode(const char *endpoint, const char *soap_action, _ns1__runCode *ns1__runCode, _ns1__runCodeResponse *ns1__runCodeResponse)
{	struct soap *soap = this;
	struct __ns1__runCode soap_tmp___ns1__runCode;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:runCode";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__runCode.ns1__runCode = ns1__runCode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__runCode(soap, &soap_tmp___ns1__runCode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__runCode(soap, &soap_tmp___ns1__runCode, "-ns1:runCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__runCode(soap, &soap_tmp___ns1__runCode, "-ns1:runCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__runCodeResponse)
		return soap_closesock(soap);
	ns1__runCodeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__runCodeResponse->soap_get(soap, "ns1:runCodeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Start(const char *endpoint, const char *soap_action, _ns1__Start *ns1__Start, _ns1__StartResponse *ns1__StartResponse)
{	struct soap *soap = this;
	struct __ns1__Start soap_tmp___ns1__Start;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Start";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Start.ns1__Start = ns1__Start;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Start(soap, &soap_tmp___ns1__Start);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Start(soap, &soap_tmp___ns1__Start, "-ns1:Start", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Start(soap, &soap_tmp___ns1__Start, "-ns1:Start", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StartResponse)
		return soap_closesock(soap);
	ns1__StartResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StartResponse->soap_get(soap, "ns1:StartResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Status(const char *endpoint, const char *soap_action, _ns1__Status *ns1__Status, _ns1__StatusResponse *ns1__StatusResponse)
{	struct soap *soap = this;
	struct __ns1__Status soap_tmp___ns1__Status;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Status";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Status.ns1__Status = ns1__Status;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Status(soap, &soap_tmp___ns1__Status);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Status(soap, &soap_tmp___ns1__Status, "-ns1:Status", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Status(soap, &soap_tmp___ns1__Status, "-ns1:Status", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StatusResponse)
		return soap_closesock(soap);
	ns1__StatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StatusResponse->soap_get(soap, "ns1:StatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Stop(const char *endpoint, const char *soap_action, _ns1__Stop *ns1__Stop, _ns1__StopResponse *ns1__StopResponse)
{	struct soap *soap = this;
	struct __ns1__Stop soap_tmp___ns1__Stop;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Stop";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Stop.ns1__Stop = ns1__Stop;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Stop(soap, &soap_tmp___ns1__Stop);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Stop(soap, &soap_tmp___ns1__Stop, "-ns1:Stop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Stop(soap, &soap_tmp___ns1__Stop, "-ns1:Stop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StopResponse)
		return soap_closesock(soap);
	ns1__StopResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StopResponse->soap_get(soap, "ns1:StopResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::getName_(const char *endpoint, const char *soap_action, _ns1__getName *ns1__getName, _ns1__getNameResponse *ns1__getNameResponse)
{	struct soap *soap = this;
	struct __ns1__getName_ soap_tmp___ns1__getName_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:getName";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getName_.ns1__getName = ns1__getName;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getName_(soap, &soap_tmp___ns1__getName_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getName_(soap, &soap_tmp___ns1__getName_, "-ns1:getName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getName_(soap, &soap_tmp___ns1__getName_, "-ns1:getName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getNameResponse)
		return soap_closesock(soap);
	ns1__getNameResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__getNameResponse->soap_get(soap, "ns1:getNameResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::runCode_(const char *endpoint, const char *soap_action, _ns1__runCode *ns1__runCode, _ns1__runCodeResponse *ns1__runCodeResponse)
{	struct soap *soap = this;
	struct __ns1__runCode_ soap_tmp___ns1__runCode_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:runCode";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__runCode_.ns1__runCode = ns1__runCode;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__runCode_(soap, &soap_tmp___ns1__runCode_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__runCode_(soap, &soap_tmp___ns1__runCode_, "-ns1:runCode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__runCode_(soap, &soap_tmp___ns1__runCode_, "-ns1:runCode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__runCodeResponse)
		return soap_closesock(soap);
	ns1__runCodeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__runCodeResponse->soap_get(soap, "ns1:runCodeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Start_(const char *endpoint, const char *soap_action, _ns1__Start *ns1__Start, _ns1__StartResponse *ns1__StartResponse)
{	struct soap *soap = this;
	struct __ns1__Start_ soap_tmp___ns1__Start_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Start";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Start_.ns1__Start = ns1__Start;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Start_(soap, &soap_tmp___ns1__Start_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Start_(soap, &soap_tmp___ns1__Start_, "-ns1:Start", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Start_(soap, &soap_tmp___ns1__Start_, "-ns1:Start", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StartResponse)
		return soap_closesock(soap);
	ns1__StartResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StartResponse->soap_get(soap, "ns1:StartResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Status_(const char *endpoint, const char *soap_action, _ns1__Status *ns1__Status, _ns1__StatusResponse *ns1__StatusResponse)
{	struct soap *soap = this;
	struct __ns1__Status_ soap_tmp___ns1__Status_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Status";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Status_.ns1__Status = ns1__Status;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Status_(soap, &soap_tmp___ns1__Status_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Status_(soap, &soap_tmp___ns1__Status_, "-ns1:Status", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Status_(soap, &soap_tmp___ns1__Status_, "-ns1:Status", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StatusResponse)
		return soap_closesock(soap);
	ns1__StatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StatusResponse->soap_get(soap, "ns1:StatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int ServiceSoapBindingProxy::Stop_(const char *endpoint, const char *soap_action, _ns1__Stop *ns1__Stop, _ns1__StopResponse *ns1__StopResponse)
{	struct soap *soap = this;
	struct __ns1__Stop_ soap_tmp___ns1__Stop_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://192.168.56.11/test/ws/service.1cws";
	if (soap_action == NULL)
		soap_action = "http://localhost/service#Service:Stop";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__Stop_.ns1__Stop = ns1__Stop;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__Stop_(soap, &soap_tmp___ns1__Stop_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__Stop_(soap, &soap_tmp___ns1__Stop_, "-ns1:Stop", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__Stop_(soap, &soap_tmp___ns1__Stop_, "-ns1:Stop", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__StopResponse)
		return soap_closesock(soap);
	ns1__StopResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__StopResponse->soap_get(soap, "ns1:StopResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
